---
title: "RLadies Workshop"
author: "Emma Garlock"
date: "11/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)
library(ggplot2)
library(dplyr)
library(plotly)
library(here)
library(ggmap)
library(viridis)
library(rgeos)
library(maptools)
library(maps)
library(sf)
library(readr)
library(tidyverse)
select <- dplyr::select
```

```{r readData}

data <- read_csv(here("data","affiliations_lat_long.csv"))
data <- data %>% 
       select(-X1) %>% distinct() %>%
        drop_na() %>%
        separate(latlong,c("lat","long"),sep=",") %>%
        mutate_at(c("lat","long"),
                  function(str) as.numeric(unlist(regmatches(str,gregexpr("(?>-)*[[:digit:]]+\\.*[[:digit:]]*",str, perl=TRUE))))
                  )
# Convert to simple feature object
point_sf <- st_as_sf(data, coords = c("long", "lat"), crs = 4326)

```
```{r worldmapdatamanipulation}

# Get world map data
worldmap <- maps::map("world", fill = TRUE, plot = FALSE)

# Convert world to sp class
IDs <- sapply(strsplit(worldmap$names, ":"), "[", 1L)
world_sp <- map2SpatialPolygons(worldmap, IDs = IDs, 
                                proj4string = CRS("+proj=longlat +datum=WGS84"))

# Convert world_sp to simple feature object
world_sf <- st_as_sf(world_sp)

# Add country ID
world_sf <- world_sf %>%
  mutate(region = map_chr(1:length(world_sp@polygons), function(i){
    world_sp@polygons[[i]]@ID
  }))
#this step takes a while 
#result <- st_within(point_sf, world_sf, sparse = FALSE)
result=read.csv(here("workshop","data","result.csv"))
result=result[,-1]
# Calculate the total count of each polygon
# Store the result as a new column "Count" in world_sf
world_sf <- world_sf %>%
  mutate(Count = apply(result, 2, sum))

# most popular topic per country
resultWithTopic <- cbind(point_sf$topic,result)
topicSummary <- resultWithTopic %>% as.data.frame(stringsAsFactors=FALSE) %>% 
        group_by(V1) %>% 
        dplyr::summarise_all(function(x)sum(x != "FALSE"))
names(topicSummary) <- c("topic",world_sf$region)   

topicSummary <- topicSummary %>% gather(region,count,-topic)
topicRanks <- topicSummary %>% 
      filter(count != 0) %>%
        group_by(region) %>% 
      summarise(topicMax=list(topic[count==max(count)])) %>%
      rowwise() %>%
      mutate(topicDisplay=ifelse(length(unlist(topicMax))>1,
                                 "multiple",topicMax),
             text = paste(unique(unlist(topicMax)),collapse = ", "))

# Convert world_sf to a data frame world_df 
world_df <- world_sf
st_geometry(world_df) <- NULL

# Get world data frame
world_data <- map_data("world")

# Merge world_data and world_df and topicRanks
world_data2=read.csv(here("workshop","data","world_data2.csv"))
#world_data2 <- world_data %>%
  #left_join(world_df, by = c("region"))%>%
 #left_join(topicRanks, by=c("region"))
#world_data2=data.frame(lapply(world_data2,as.character),stringsAsFactors=FALSE)
```
```{r}

```

```{r worldmap}
pl <- ggplot() + 
  geom_polygon(data = world_data2, aes(x = long, y = lat, group=group,fill =log(Count),text=Count))+
  #geom_point(data=data,aes(x = long, y = lat),alpha=0.5,size=0.5,colour="grey")+
  coord_fixed(1.3)+
  scale_fill_viridis()+
  theme_void()

ggplotly(pl,tooltip = "text")

## R Markdown
```

```{r}
###get only europe
#world_sf=read.csv(here("workshop","data","world_sf.csv"))

filt_bbox <- sf::st_bbox(c(xmin = -9, 
                           ymin = 36, 
                           xmax = 42.5, 
                           ymax = 70.1), 
                         crs = st_crs(4326)) %>% 
  sf::st_as_sfc(.)


find_data <- sf::st_within(world_sf, filt_bbox)
#> although coordinates are longitude/latitude, st_within assumes that they are planar
europe_sf <- world_sf[which(lengths(find_data) != 0), ]

europe_result <- st_within(point_sf, europe_sf, sparse = FALSE)

# Calculate the total count of each polygon
# Store the result as a new column "Count" in world_sf
europe_sf <- europe_sf %>%
  mutate(Count = apply(europe_result, 2, sum))

# Convert world_sf to a data frame world_df 
europe_df <- europe_sf
st_geometry(europe_df) <- NULL

# Get world data frame
world_data <- map_data("world")

# Merge world_data and world_df
europe_data <- europe_df %>%
  left_join(world_data, by = c("region"))

ind <- sf::st_intersects(point_sf, europe_sf)
points_europe<-  point_sf[which(lengths(ind) != 0), ]
points_europe <- cbind(points_europe,st_coordinates(points_europe))
points_europe=points_europe[,-c(6,7)]
```

```{r}
head(europe_data)
colnames(points_europe)
```

```{r}
pl <- ggplot() + 
  geom_polygon(data = europe_data, aes(x = long, y = lat, group = group, fill = log(Count),text=paste(region,Count, sep=";"))) +
  geom_point(data=points_europe,aes(x=X,y=Y,text=str_wrap(affiliation,50)),alpha=0.5,size=0.5,colour="grey")+
  coord_fixed(1.3)+
  scale_fill_viridis()+
  theme_void()

ggplotly(pl,tooltip="text")
```
```



